#!/bin/bash

if command -v podman &> /dev/null; then
    COMMAND=podman
elif command -v docker &> /dev/null; then
    COMMAND=docker
else
    echo "Error: Neither podman nor docker found. Please install one of them."
    exit 1
fi

$COMMAND run -it --rm --hostname php-devbox -v $(pwd):/workspace php-devbox:latest bash
